// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"mini-market/src/core/application/services"
	"mini-market/src/entrypoint/asynctask"
	"mini-market/src/entrypoint/http"
	"mini-market/src/entrypoint/http/interceptor/middlewares"
	"mini-market/src/infrastructure/asyncq"
	middlewares2 "mini-market/src/infrastructure/asyncq/middlewares"
	"mini-market/src/infrastructure/echohttp"
	"mini-market/src/infrastructure/echohttp/defaults"
	"mini-market/src/infrastructure/echohttp/defaults/handlers"
	"mini-market/src/infrastructure/env"
	"mini-market/src/infrastructure/logger"
	"mini-market/src/infrastructure/notification"
	"mini-market/src/infrastructure/redis"
	"mini-market/src/infrastructure/security"
	"mini-market/src/infrastructure/sentry"
	"mini-market/src/infrastructure/telemetry"
)

// Injectors from wire.go:

func InitHttpApp() *http.App {
	requestValidator := defaults.NewRequestValidator()
	echo := echohttp.NewEcho(requestValidator)
	envEnv := env.NewEnv()
	redisClientOpt := async.NewAsynqRedisClientOpt0(envEnv)
	httpHandler := handlers.NewAsynqmonHandler(redisClientOpt)
	developmentGroup := defaults.NewDevelopmentGroup(httpHandler)
	developerUserBasicAuthMiddleware := defaults.NewDeveloperUserBasicAuthMiddleware(envEnv)
	role := _wireRoleValue
	telemetryTelemetry := telemetry.NewTelemetry(envEnv, role)
	client := sentry.NewClient(envEnv, role)
	httpLogger := logger.NewHttpLogger(telemetryTelemetry, client)
	recoveryMiddleware := defaults.NewRecoveryMiddleware(httpLogger)
	httpLoggerMiddleware := defaults.NewHttpLoggerMiddleware(httpLogger)
	consoleLogger := logger.NewConsoleLogger()
	consoleLoggerMiddleware := defaults.NewConsoleLoggerMiddleware(consoleLogger)
	errorRecorderMiddleware := defaults.NewErrorRecorderMiddleware()
	httpServer := echohttp.NewEchoServerImpl(echo, envEnv, developmentGroup, developerUserBasicAuthMiddleware, recoveryMiddleware, httpLoggerMiddleware, consoleLoggerMiddleware, errorRecorderMiddleware)
	jwtTokenProvider := security.NewJwtTokenAdapter(envEnv)
	configProvider := env.NewConfigAdapter(envEnv)
	userAuthTokenService := services.NewUserAuthTokenService(jwtTokenProvider, configProvider)
	redisClient := redis.NewRedisClient(envEnv)
	sessionDenylist := redis.NewSessionDenylistImpl(redisClient)
	jwtAuthMiddleware := middlewares.NewJwtAuthMiddleware(userAuthTokenService, sessionDenylist)
	responseMiddleware := middlewares.NewResponseMiddleware()
	limiter := redis.NewRateLimiterImpl(redisClient)
	rateLimitMiddleware := middlewares.NewRateLimitMiddleware(limiter)
	app := http.NewApp(httpServer, envEnv, jwtAuthMiddleware, responseMiddleware, rateLimitMiddleware, telemetryTelemetry, client, httpLogger)
	return app
}

var (
	_wireRoleValue = telemetry.RoleHTTP
)

func InitAsyncApp() *asynctask.App {
	config := async.NewAsynqConfig()
	envEnv := env.NewEnv()
	redisClientOpt := async.NewAsynqRedisClientOpt0(envEnv)
	server := async.NewAsynqServer(config, redisClientOpt)
	serveMux := async.NewAsynqServeMux()
	consoleLogger := logger.NewConsoleLogger()
	role := _wireTelemetryRoleValue
	telemetryTelemetry := telemetry.NewTelemetry(envEnv, role)
	client := sentry.NewClient(envEnv, role)
	asyncLogger := logger.NewAsyncLogger(telemetryTelemetry, client)
	taskLogMiddleware := middlewares2.NewTaskLogMiddleware(consoleLogger, asyncLogger)
	asyncContext := async.NewAsyncContextImpl()
	alertNotifier := notification.NewNoopAlertNotifier()
	taskAlertMiddleware := middlewares2.NewTaskAlertMiddleware(asyncContext, alertNotifier)
	taskTraceMiddleware := middlewares2.NewTaskTraceMiddleware(asyncLogger)
	asyncServer := async.NewAsynqServerImpl(server, serveMux, taskLogMiddleware, taskAlertMiddleware, taskTraceMiddleware)
	app := asynctask.NewAsyncApp(asyncServer, telemetryTelemetry, client)
	return app
}

var (
	_wireTelemetryRoleValue = telemetry.RoleAsync
)
