// Code generated by wireinjectgen; DO NOT EDIT.
package wire

import (
	"github.com/google/wire"
	services "mini-market/src/core/application/services"
	asynctask "mini-market/src/entrypoint/asynctask"
	http "mini-market/src/entrypoint/http"
	middlewares "mini-market/src/entrypoint/http/interceptor/middlewares"
	asyncq "mini-market/src/infrastructure/asyncq"
	middlewares2 "mini-market/src/infrastructure/asyncq/middlewares"
	db "mini-market/src/infrastructure/db"
	echohttp "mini-market/src/infrastructure/echohttp"
	defaults "mini-market/src/infrastructure/echohttp/defaults"
	handlers "mini-market/src/infrastructure/echohttp/defaults/handlers"
	env "mini-market/src/infrastructure/env"
	logger "mini-market/src/infrastructure/logger"
	notification "mini-market/src/infrastructure/notification"
	repository "mini-market/src/infrastructure/persistence/repository"
	redis "mini-market/src/infrastructure/redis"
	security "mini-market/src/infrastructure/security"
	sentry "mini-market/src/infrastructure/sentry"
	telemetry "mini-market/src/infrastructure/telemetry"
)

var ProviderSet = wire.NewSet(
	services.NewUserAuthTokenService,
	asynctask.NewAsyncApp,
	http.NewApp,
	middlewares.NewJwtAuthMiddleware,
	middlewares.NewRateLimitMiddleware,
	middlewares.NewResponseMiddleware,
	asyncq.NewAsyncContextImpl,
	asyncq.NewAsynqConfig,
	asyncq.NewAsynqInspector,
	asyncq.NewAsynqRedisClientOpt0,
	asyncq.NewAsynqServeMux,
	asyncq.NewAsynqServer,
	asyncq.NewAsynqServerImpl,
	asyncq.NewAsynqTaskPublisher,
	asyncq.NewtAsynqClient,
	middlewares2.NewTaskAlertMiddleware,
	middlewares2.NewTaskLogMiddleware,
	middlewares2.NewTaskTraceMiddleware,
	db.NewAtomicTxImpl,
	db.NewDatabase,
	db.NewGormDB,
	echohttp.NewEcho,
	echohttp.NewEchoServerImpl,
	defaults.NewConsoleLoggerMiddleware,
	defaults.NewDeveloperUserBasicAuthMiddleware,
	defaults.NewDevelopmentGroup,
	defaults.NewErrorRecorderMiddleware,
	defaults.NewHttpLoggerMiddleware,
	defaults.NewRecoveryMiddleware,
	defaults.NewRequestValidator,
	handlers.NewAsynqmonHandler,
	env.NewConfigAdapter,
	env.NewEnv,
	logger.NewAsyncLogger,
	logger.NewConsoleLogger,
	logger.NewGatewayLogger,
	logger.NewHttpLogger,
	notification.NewNoopAlertNotifier,
	repository.NewAuthSessionRepositoryImpl,
	repository.NewBaseRepository,
	repository.NewUserRepositoryImpl,
	redis.NewRateLimiterImpl,
	redis.NewRedisClient,
	redis.NewSessionDenylistImpl,
	security.NewBcryptAdapter,
	security.NewJwtTokenAdapter,
	sentry.NewClient,
	telemetry.NewQueueMetrics,
	telemetry.NewTelemetry,
)
